### ISSUE TITLE
Hosted API returning json that unescape double quotes

### ISSUE THREAD

**Issue by mamat-rahmat** [Hipo/university-domains-list-api#1]
Some of the university name use double quotes. The [Hosted API](http://universities.hipolabs.com/) returning json that unescape double quotes creating invalid json.

I tried to investigate. But, when i run this app locally error arise from 404 response of endpoint `https://raw.githubusercontent.com/Hipo/university-domains-list-api/master/world_universities_and_domains.json`. I though the endpoint should be `https://raw.githubusercontent.com/Hipo/university-domains-list/master/world_universities_and_domains.json`

After fixing this i found that the json result is ok. I think this repo is not updated with Hosted API. Is it?

**Comment by yigitguler** [comment]
That might be true. We will check as soon as possible.
