### ISSUE TITLE
Multiple words search

### ISSUE THREAD

**Issue by e-naharnovic** [Hipo/university-domains-list-api#11]
Is it possible to add search with multiple words like `http://universities.hipolabs.com/search?name=Internal%20Affairs` ? Now an empty result is returned but there are 2 universities for sure including this name

**Comment by e-naharnovic** [comment]
@yigitguler could you help to answer this question please?

**Comment by yigitguler** [comment]
@e-naharnovic There is definitely something wrong. 

http://universities.hipolabs.com/search?name=sabanci+university

This multiple word combination successfully returns the appropriate result.

We will welcome a PR that fixes this.

Thanks.

**Comment by e-naharnovic** [comment]
@yigitguler in your example with `sabanci university` those 2 words make the whole name of the university and it works fine. What about partial match like only 2 words in request but the name contains 3 or more?

**Comment by yigitguler** [comment]
Yeah, apparently the system is designed for typeahead inputs

If you enter "saban" as the query parameter, it successfully finds the correct university.
However, it doesn't bring any results if you enter "aban".

I think the system should support an alternative search system that supports something similar to `ILIKE` command.

**Comment by e-naharnovic** [comment]
@yigitguler Thanks for explanations. My use cases concern more requests like 'Middle East', 'Civil Aviation' etc. that can be at the beginning/middle/end of universities names .
I have a branch with my version of code when above-mentioned cases are matched. Could you give me access to push and create PR? and probably you could give your feedback about it?

**Comment by yigitguler** [comment]
Yep, you can directly open a PR from your fork to this repo.
