### ISSUE TITLE
Using hosted API is blocked by CORS

### ISSUE THREAD

**Issue by rizdaputra** [Hipo/university-domains-list-api#12]
I am trying to use the hosted API but blocked by CORS. Can you open it, or is it my config that is wrong?

**Comment by yigitguler** [comment]
Yes, we can open it.

**Comment by ashley-how** [comment]
Hi, The API is blocked by CORS. Can I check with the API is opened? Thanks!

**Comment by yigitguler** [comment]
This is completed now.
