### ISSUE TITLE
Universities duplicates

### ISSUE THREAD

**Issue by andry900** [Hipo/university-domains-list-api#15]
All the universities in the JSON are now duplicated!!

**Comment by yigitguler** [comment]
http://universities.hipolabs.com/search?name=sabanci

the resuts are not duplicated.

**Comment by yigitguler** [comment]
Please provide more information.

**Comment by andry900** [comment]
Try this: http://universities.hipolabs.com/search?country=turkey
All the universities are duplicate in every country. I have an autocomplete edit text in my android app with all the italian universities that worked till last days. Yesterday we noticed that all the universities are duplicated...

**Comment by andry900** [comment]
![app](https://user-images.githubusercontent.com/32498406/77910718-e53b9b00-728f-11ea-944b-bbfb343a639c.jpg)

**Comment by yigitguler** [comment]
Weird. I restarted the server, and now it doesn't return duplicate results.
