### ISSUE TITLE
alpha_two_code query returns whole data

### ISSUE THREAD

**Issue by ycd** [Hipo/university-domains-list-api#16]
When you send a request to the server with `alpha_two_code` query it returns the whole data, can not filters it.

I checked it with multiple params, it happens in every request. [Example](http://universities.hipolabs.com/search?alpha_two_code=il)

**Comment by yigitguler** [comment]
alpha_two_code search is not supported yet. You can open a PR.

**Comment by ycd** [comment]
Just realized it.
