### ISSUE TITLE
Frequency of world_universities_and_domains.json refreshed on the server?

### ISSUE THREAD

**Issue by jagbarcelo** [Hipo/university-domains-list-api#25]
We have asked for an addition to the list of Universities, and it is approved and merged (see https://github.com/Hipo/university-domains-list/issues/491 ). However, when we request for [http://universities.hipolabs.com/search?domain=cust.edu.pk](http://universities.hipolabs.com/search?domain=cust.edu.pk), it still returns no results.

Which is the frequency of the updates to the repository being moved upon to the published API (the one hosted on Hipo)? Am I missing something?

**Comment by yigitguler** [comment]
You can call this endpoint, to update the API: http://universities.hipolabs.com/update. If you open a PR that will add this to the automation of this repo, we can happily approve.
