### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by bansal-harsh-2504** [Hipo/university-domains-list-api#28]
i wanted to get names of universities in India based on the state name. But i am doing something wrong. it just gives me all universities in India and ignores the state provided. i am doing this with the help of query strings. can  you please help me.

let url = "http://universities.hipolabs.com/search?country=india&state-province=";
is there anything wrong with url.
btn.addEventListener("click", async()=>{
    list.innerText = "";
    let state = document.querySelector("#search").value;
    let colleges = await getUniversity(state);
    for(college of colleges){
         let li = document.createElement("li");
         li.innerText = college.name;
         list.appendChild(li);
     }
});

**Comment by poojaBalsara** [comment]
Hope this can help you also please do check you URL again its  incorrect .

//html code
<input placeholder="Enter state name">
<button>Search</button>
<ul id="list"></ul>
<script src="https://cdn.jsdelivr.net/npm/axios@1.1.2/dist/axios.min.js"></script>


//Javascript 
let url="http://universities.hipolabs.com/search?name=";
let btn=document.querySelector("button");

btn.addEventListener("click",async()=>{
    let state=document.querySelector("input").value;
    let colleges=await getColleges(state,"india");
    show(colleges);
});

function show(colleges){
    let list=document.querySelector("#list");
    list.innerText="";
    for(col of colleges){
        let li=document.createElement("li");
        li.innerText=col.name;
        list.appendChild(li);
    }
}

async function getColleges(state,country){
    try{
       let res= await axios.get(url + state +"&country="+ country);
       console.log(state);
       return res.data;
    }catch(err){
        console.log(err);
        return [];

    }
}

**Comment by poojaBalsara** [comment]
Hope this can help you also please do check you URL again its incorrect .

//html code
//<input placeholder="Enter state name">
//<button>Search</button>
//<ul id="list"></ul>
//<script src="https://cdn.jsdelivr.net/npm/axios@1.1.2/dist/axios.min.js"></script>

//Javascript
let url="http://universities.hipolabs.com/search?name=";
let btn=document.querySelector("button");

btn.addEventListener("click",async()=>{
let state=document.querySelector("input").value;
let colleges=await getColleges(state,"india");
show(colleges);
});

function show(colleges){
let list=document.querySelector("#list");
list.innerText="";
for(col of colleges){
let li=document.createElement("li");
li.innerText=col.name;
list.appendChild(li);
}
}

async function getColleges(state,country){
try{
let res= await axios.get(url + state +"&country="+ country);
console.log(state);
return res.data;
}catch(err){
console.log(err);
return [];

}
}

**Comment by poojaBalsara** [comment]
Hope this can help you also check your URL again its incorrect.

let url="http://universities.hipolabs.com/search?name=";
let btn=document.querySelector("button");

btn.addEventListener("click",async()=>{
    let state=document.querySelector("input").value;
    let colleges=await getColleges(state,"india");
    show(colleges);
});

function show(colleges){
    let list=document.querySelector("#list");      //list is an id for ul tag
    list.innerText="";
    for(col of colleges){
        let li=document.createElement("li");
        li.innerText=col.name;
        list.appendChild(li);
    }
}

async function getColleges(state,country){
    try{
       let res= await axios.get(url + state +"&country="+ country);
       console.log(state);
       return res.data;
    }catch(err){
        console.log(err);
        return [];

    }
}
