### ISSUE TITLE
Domain filtering unexpected results.

### ISSUE THREAD

**Issue by kade-robertson** [Hipo/university-domains-list-api#4]
Wasn't sure if I should keep this as part of the same issue, but this does not seem to be working as intended. For example, if I was to make a request to filter by the domain 'mit.edu', I would expect only one result would appear as an exact match, or at most 3 for also matching 'mit.edu' within the complete domain. However, the filtering seems to have no effect whatsoever, as all 9601 results are returned with this:
```
http://universities.hipolabs.com/search?domain=mit.edu
```

**Comment by yigitguler** [comment]
Thanks for reporting. This is fixed:
http://universities.hipolabs.com/search?domain=mit.edu


http://universities.hipolabs.com/search?domain=fuzzy brings empty result
