### ISSUE TITLE
API Doesn't Update when JSON is Updated

### ISSUE THREAD

**Issue by dl-eric** [Hipo/university-domains-list-api#7]
Currently, the server only loads the data once in its lifetime. This means that the server needs to be restarted in order to refresh its college list.

I'm adding this issue to begin discussion to mitigate this. I am unsure if maintainers would want to manually restart the server every time the list is updated, so I'm proposing that we create an endpoint that would force a refresh. To prevent malicious spamming of the endpoint, we can enforce that the server at most refreshes the data once every 24 hours.

**Comment by yigitguler** [comment]
This is a good idea. PR will be appreciated :)

**Comment by dl-eric** [comment]
Now that this has been merged, is it possible to update the public API?

**Comment by yigitguler** [comment]
Done!

**Comment by yigitguler** [comment]
Thank you.

**Comment by dl-eric** [comment]
Huge thanks!
